micronaut:
  application:
    name: backend
  server:
    port: ${devmarkt.server.port:8080}
    host: ${devmarkt.server.host:`localhost`}
datasources:
  default:
    url: jdbc:postgresql://${devmarkt.postgres.host:localhost}:${devmarkt.postgres.port:5432}/${devmarkt.postgres.database}
    username: ${devmarkt.postgres.user}
    password: ${devmarkt.postgres.password}
flyway:
  clean-schema: true
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migrations
graphql:
  enabled: true
  path: "/graphql"
  schemas: /graphql
  graphiql:
    enabled: true
    path: "/graphiql"
