name: Danger Review

on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Danger Review
        uses: danger/danger-js@main
        timeout-minutes: 15
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
